import { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/dashboard/AppSidebar";
import { VersionFooter } from "@/components/dashboard/VersionFooter";
import { ArrowLeft, Router, Monitor, HardDrive, Radio, Wifi, Cpu, ChevronDown, ChevronRight, Copy, Save, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { useAutoLogout } from "@/hooks/use-auto-logout";
import { useHostingMode } from "@/hooks/use-hosting-mode";
import { toast } from "sonner";

const typeIcons: Record<string, any> = {
  OLT: Router, MikroTik_Router: Router, MikroTik_Switch: Monitor,
  Linux_Server: HardDrive, Windows_Server: HardDrive, CPE: Radio,
  Access_Point: Wifi, Other: Cpu,
};

const DeviceDetail = () => {
  useAutoLogout();
  const navigate = useNavigate();
  const { id } = useParams();
  const { hostingMode } = useHostingMode();
  const [user, setUser] = useState<any>(null);
  const [isAdminOrAbove, setIsAdminOrAbove] = useState(false);
  const [device, setDevice] = useState<any>(null);
  const [interfaces, setInterfaces] = useState<any[]>([]);
  const [ipAssignments, setIpAssignments] = useState<any[]>([]);
  const [vlans, setVlans] = useState<any[]>([]);
  const [routes, setRoutes] = useState<any[]>([]);
  const [expandedIfaces, setExpandedIfaces] = useState<Set<string>>(new Set());
  const [nocNotes, setNocNotes] = useState("");
  const [savingNotes, setSavingNotes] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const init = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) { navigate("/auth"); return; }
      setUser(session.user);
      const { data: roleData } = await supabase.from("user_roles").select("role").eq("user_id", session.user.id).single();
      if (roleData && (roleData.role === "admin" || roleData.role === "superadmin")) setIsAdminOrAbove(true);
      fetchDevice();
    };
    init();
  }, [id, navigate]);

  const fetchDevice = async () => {
    if (!id) return;
    setLoading(true);
    const [devRes, ifRes, ipRes, vlanRes, routeRes] = await Promise.all([
      supabase.from("devices").select("*").eq("id", id).single(),
      supabase.from("interfaces").select("*").eq("device_id", id).order("sort_order"),
      supabase.from("ip_assignments").select("*").eq("device_id", id),
      supabase.from("vlans").select("*").eq("device_id", id).order("vlan_id"),
      supabase.from("static_routes").select("*").eq("device_id", id),
    ]);
    if (devRes.data) {
      setDevice(devRes.data);
      setNocNotes(devRes.data.noc_notes || "");
    }
    setInterfaces(ifRes.data || []);
    setIpAssignments(ipRes.data || []);
    setVlans(vlanRes.data || []);
    setRoutes(routeRes.data || []);
    // Expand all interfaces by default
    if (ifRes.data) setExpandedIfaces(new Set(ifRes.data.map((i: any) => i.id)));
    setLoading(false);
  };

  const toggleIface = (ifId: string) => {
    const next = new Set(expandedIfaces);
    next.has(ifId) ? next.delete(ifId) : next.add(ifId);
    setExpandedIfaces(next);
  };

  const saveNotes = async () => {
    if (!id) return;
    setSavingNotes(true);
    await supabase.from("devices").update({ noc_notes: nocNotes }).eq("id", id);
    toast.success("Notes saved");
    setSavingNotes(false);
  };

  const generateConfig = () => {
    if (!device) return;
    const lines = [
      `# Auto-generated by Nosteq IP Monitor`,
      `# Device: ${device.name} | Generated: ${new Date().toLocaleString("en-KE", { timeZone: "Africa/Nairobi" })}`,
      ``,
    ];

    if (ipAssignments.length > 0) {
      lines.push(`/ip address`);
      for (const ip of ipAssignments) {
        const iface = interfaces.find((i) => i.id === ip.interface_id);
        lines.push(`add address=${ip.ip_address} interface=${iface?.name || "unknown"} comment="${ip.role}"`);
      }
      lines.push(``);
    }

    if (vlans.length > 0) {
      lines.push(`/interface vlan`);
      for (const v of vlans) {
        const iface = interfaces.find((i) => i.id === v.interface_id);
        lines.push(`add interface=${iface?.name || "bridge1"} name=vlan${v.vlan_id} vlan-id=${v.vlan_id}`);
      }
      lines.push(``);
    }

    if (routes.length > 0) {
      lines.push(`/ip route`);
      for (const r of routes) {
        lines.push(`add dst-address=${r.destination} gateway=${r.gateway}${r.comment ? ` comment="${r.comment}"` : ""}`);
      }
    }

    navigator.clipboard.writeText(lines.join("\n"));
    toast.success("MikroTik config copied to clipboard");
  };

  if (!user || loading) return null;
  if (!device) return <div className="text-foreground p-8">Device not found</div>;

  const Icon = typeIcons[device.type] || Cpu;
  const monitoredIps = ipAssignments.filter((ip) => ip.monitor_uptime);
  const upCount = monitoredIps.filter((ip) => ip.last_status === "up").length;
  const downCount = monitoredIps.filter((ip) => ip.last_status === "down").length;
  const blacklistCount = ipAssignments.reduce((s, ip) => s + (ip.blacklist_count || 0), 0);

  return (
    <SidebarProvider>
      <div className="min-h-screen flex w-full">
        <AppSidebar activeTab="devices" onTabChange={(tab) => {
          if (tab === "monitor") navigate("/dashboard");
          else if (tab === "devices") navigate("/devices");
        }} isAdminOrAbove={isAdminOrAbove} userEmail={user.email} />

        <div className="flex-1 flex flex-col min-w-0">
          <header className="h-[60px] flex items-center justify-between px-4 border-b border-border/50 bg-background/95 backdrop-blur-xl sticky top-0 z-50">
            <div className="flex items-center gap-3">
              <SidebarTrigger className="text-muted-foreground hover:text-foreground" />
              <Button variant="ghost" size="sm" onClick={() => navigate("/devices")}><ArrowLeft className="h-4 w-4" /></Button>
              <div>
                <h1 className="text-base font-semibold text-foreground">{device.name}</h1>
                <p className="text-[11px] text-muted-foreground">{(device.type || "").replace(/_/g, " ")} • {device.site_name || "No site"}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" className="h-8 text-xs" onClick={generateConfig}>
                <Copy className="h-3.5 w-3.5 mr-1" /> Generate Config
              </Button>
            </div>
          </header>

          {/* Sticky quick stats */}
          <div className="flex items-center gap-4 px-4 py-2 border-b border-border/30 bg-card/50 backdrop-blur text-xs">
            <span className="text-success font-medium">{upCount} UP</span>
            <span className="text-destructive font-medium">{downCount} DOWN</span>
            <span className="text-warning font-medium">🛡 {blacklistCount} Blacklisted</span>
            <span className="text-muted-foreground">{vlans.length} VLANs</span>
          </div>

          <main className="flex-1 p-4 md:p-6 overflow-auto space-y-6 animate-in fade-in duration-200">

            {/* Overview Cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {[
                { label: "Interfaces", value: interfaces.length, color: "text-primary" },
                { label: "Monitored IPs", value: monitoredIps.length, color: "text-primary" },
                { label: "VLANs", value: vlans.length, color: "text-accent" },
                { label: "7d Uptime", value: "—", color: "text-success" },
              ].map((card) => (
                <div key={card.label} className="bg-card border border-border rounded-xl p-4 text-center">
                  <p className={cn("text-2xl font-bold", card.color)}>{card.value}</p>
                  <p className="text-xs text-muted-foreground">{card.label}</p>
                </div>
              ))}
            </div>

            {/* Interfaces & IP Assignments */}
            <div>
              <h2 className="text-lg font-semibold text-foreground mb-3">Network Interfaces</h2>
              {interfaces.length === 0 ? (
                <p className="text-sm text-muted-foreground">No interfaces documented yet.</p>
              ) : (
                <div className="space-y-3">
                  {interfaces.map((iface) => {
                    const ifIPs = ipAssignments.filter((ip) => ip.interface_id === iface.id);
                    const ifVlans = vlans.filter((v) => v.interface_id === iface.id);
                    const expanded = expandedIfaces.has(iface.id);

                    return (
                      <div key={iface.id} className="border border-border rounded-xl overflow-hidden">
                        <button className="w-full flex items-center justify-between p-3 hover:bg-muted/30 transition" onClick={() => toggleIface(iface.id)}>
                          <div className="flex items-center gap-2">
                            {expanded ? <ChevronDown className="h-4 w-4 text-muted-foreground" /> : <ChevronRight className="h-4 w-4 text-muted-foreground" />}
                            <span className="font-mono font-semibold text-sm text-foreground">{iface.name}</span>
                            <Badge variant="outline" className="text-[10px]">{iface.type}</Badge>
                            {iface.is_public && <Badge className="text-[10px] bg-primary/20 text-primary border-0">Public</Badge>}
                          </div>
                          <span className="text-xs text-muted-foreground">{iface.description || ""}</span>
                        </button>

                        {expanded && (
                          <div className="px-4 pb-4 space-y-3">
                            {iface.mac_address && <p className="text-xs text-muted-foreground">MAC: {iface.mac_address} {iface.speed ? `| Speed: ${iface.speed}` : ""}</p>}

                            {ifIPs.length > 0 && (
                              <div className="space-y-2">
                                <p className="text-xs font-medium text-muted-foreground">IP Assignments</p>
                                {ifIPs.map((ip) => (
                                  <div key={ip.id} className="bg-muted/20 rounded-lg p-3 border border-border/50">
                                    <div className="flex items-center justify-between">
                                      <div className="flex items-center gap-2">
                                        <div className={cn("h-2 w-2 rounded-full", ip.last_status === "up" ? "bg-success" : ip.last_status === "down" ? "bg-destructive animate-pulse" : "bg-muted-foreground")} />
                                        <span className="font-mono font-semibold text-sm text-foreground">{ip.ip_address}</span>
                                        <Badge variant="outline" className="text-[10px]">{ip.role}</Badge>
                                        <Badge variant="outline" className="text-[10px]">{ip.ip_type}</Badge>
                                      </div>
                                      <div className="flex items-center gap-2 text-xs">
                                        {ip.last_ping_ms != null && <span className="text-muted-foreground">{ip.last_ping_ms}ms</span>}
                                        {ip.is_public ? <span className="text-primary">🌐 Public</span> : <span>🏠 Local</span>}
                                        {ip.blacklist_count > 0 && <span className="text-destructive">🛡 {ip.blacklist_count}</span>}
                                      </div>
                                    </div>
                                    {ip.last_ping_at && <p className="text-[10px] text-muted-foreground mt-1">Last checked: {new Date(ip.last_ping_at).toLocaleString("en-KE", { timeZone: "Africa/Nairobi" })}</p>}
                                  </div>
                                ))}
                              </div>
                            )}

                            {ifVlans.length > 0 && (
                              <div className="space-y-1">
                                <p className="text-xs font-medium text-muted-foreground">VLANs on this interface</p>
                                {ifVlans.map((v) => (
                                  <div key={v.id} className="flex items-center gap-3 text-xs bg-muted/10 rounded p-2">
                                    <Badge variant="outline" className="text-[10px]">VLAN {v.vlan_id}</Badge>
                                    <span className="text-foreground">{v.name || "—"}</span>
                                    <span className="text-muted-foreground">{v.subnet || ""}</span>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* VLAN Summary */}
            {vlans.length > 0 && (
              <div>
                <h2 className="text-lg font-semibold text-foreground mb-3">VLAN Summary</h2>
                <div className="border border-border rounded-xl overflow-hidden">
                  <table className="w-full text-xs">
                    <thead className="bg-muted/30">
                      <tr>
                        <th className="text-left p-2 text-muted-foreground">VLAN ID</th>
                        <th className="text-left p-2 text-muted-foreground">Name</th>
                        <th className="text-left p-2 text-muted-foreground">Subnet</th>
                        <th className="text-left p-2 text-muted-foreground">Gateway</th>
                        <th className="text-left p-2 text-muted-foreground">DHCP</th>
                        <th className="text-left p-2 text-muted-foreground">Purpose</th>
                      </tr>
                    </thead>
                    <tbody>
                      {vlans.map((v) => (
                        <tr key={v.id} className="border-t border-border/30">
                          <td className="p-2 text-foreground font-mono">{v.vlan_id}</td>
                          <td className="p-2 text-foreground">{v.name || "—"}</td>
                          <td className="p-2 text-muted-foreground font-mono">{v.subnet || "—"}</td>
                          <td className="p-2 text-muted-foreground font-mono">{v.gateway || "—"}</td>
                          <td className="p-2">{v.dhcp_enabled ? <Badge className="text-[9px] bg-success/20 text-success border-0">Yes</Badge> : "—"}</td>
                          <td className="p-2 text-muted-foreground">{v.purpose || "—"}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Static Routes */}
            {routes.length > 0 && (
              <div>
                <h2 className="text-lg font-semibold text-foreground mb-3">Static Routes</h2>
                <div className="border border-border rounded-xl overflow-hidden">
                  <table className="w-full text-xs">
                    <thead className="bg-muted/30">
                      <tr>
                        <th className="text-left p-2 text-muted-foreground">Destination</th>
                        <th className="text-left p-2 text-muted-foreground">Gateway</th>
                        <th className="text-left p-2 text-muted-foreground">Distance</th>
                        <th className="text-left p-2 text-muted-foreground">Comment</th>
                      </tr>
                    </thead>
                    <tbody>
                      {routes.map((r) => (
                        <tr key={r.id} className="border-t border-border/30">
                          <td className="p-2 text-foreground font-mono">{r.destination}</td>
                          <td className="p-2 text-foreground font-mono">{r.gateway}</td>
                          <td className="p-2 text-muted-foreground">{r.distance}</td>
                          <td className="p-2 text-muted-foreground">{r.comment || "—"}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* NOC Notes */}
            <div>
              <h2 className="text-lg font-semibold text-foreground mb-3">NOC Notes</h2>
              <Textarea className="min-h-[120px] text-sm" placeholder="Add notes about this device..." value={nocNotes} onChange={(e) => setNocNotes(e.target.value)} />
              <Button variant="outline" size="sm" className="mt-2" onClick={saveNotes} disabled={savingNotes}>
                {savingNotes ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" /> : <Save className="h-3.5 w-3.5 mr-1" />}
                Save Notes
              </Button>
            </div>

            {/* Device Info */}
            <div>
              <h2 className="text-lg font-semibold text-foreground mb-3">Device Information</h2>
              <div className="bg-card border border-border rounded-xl p-4 grid grid-cols-2 gap-3 text-sm">
                {[
                  ["Model", device.model],
                  ["Serial", device.serial_number],
                  ["OS Version", device.os_version],
                  ["Site", device.site_name],
                  ["Address", device.site_address],
                  ["Status", device.status],
                ].map(([label, val]) => (
                  <div key={label as string}>
                    <p className="text-xs text-muted-foreground">{label}</p>
                    <p className="text-foreground">{val || "—"}</p>
                  </div>
                ))}
              </div>
            </div>
          </main>
          <VersionFooter />
        </div>
      </div>
    </SidebarProvider>
  );
};

export default DeviceDetail;
